### ISSUE TITLE
Not fully synced

### ISSUE THREAD

**Issue by TheButterZone** [lirazsiri/old-blockexplorer-php#11]
https://blockexplorer.com/address/1GxpvydVQ3V8HZezPrVdp8piJzATyqA7Sx shows 2015-06-01 20:51:03 as the last TX
Noticing this on other addresses too like https://blockexplorer.com/address/1MoYfV4U61wqTPTHCyedzFmvf2o3uys2Ua

**Comment by lirazsiri** [comment]
Yes I know the site's update functionality broke. I tried rolling back the
filesystems but that didn't work out. I'd like to investigate further and
get to the bottom but unfortunately I'm in the middle of another project
that is taking up all my time.

**Comment by lirazsiri** [comment]
Address should work now. Fixed by starting over with BitPay's Insight.

**Comment by TheButterZone** [comment]
Nice.
